---
kind: pipeline
name: NGenToD GCC ARM64

clone:
  depth: 1

steps:
- name: val
  image: debian:stable-slim
  environment:
      GL_TOKEN:
        from_secret: GL_TOKEN
  commands:
    - "export GL_TOKEN"
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git wget tar
    - bash clang.sh
